Add DigipolisPopertiesAwareTrait that others can use to read property files.
digipolisgent/robo-digipolis-general pull request #2
Opened 2017-02-03 09:36 UTC by Jelle-S

2017-02-10 14:36 UTC, daften requested changes

2017-02-10 14:36 UTC, daften commented on src/Common/DigipolisPropertiesAwareInterface.php
> +<?php
Why is this interface here? A Trait (for which this is meant, looking at the methods) can't implement an interface.

2017-02-10 14:36 UTC, daften commented on src/Common/DigipolisPropertiesAware.php
> +trait DigipolisPropertiesAware
Documentation on how and when this Trait can (or should) be used, should be added in the README.md file

2017-02-13 11:28 UTC, Jelle-S commented on src/Common/DigipolisPropertiesAwareInterface.php
> +<?php
Using the trait is a way to implement the interface. You can implement the interface without using the trait. 

It's a way for us to determine if a command is 'DigipolisPropertiesAware'.

2017-02-13 12:41 UTC, daften approved these changes

2017-02-13 13:14 UTC, merged